### ISSUE TITLE
Bootstrap 4 Beta

### ISSUE THREAD

**Issue by oleteacher** [Vegetam/BoostrapPageGenerator4#2]
Greetings!

We have been using your bootstrap generator 4 in class to build simple student pages and really enjoying it.

Wondering now that the Bootstrap Team has released 4.0.0-beta.2 will you be updating your generator?

The Bootstrap Team says there will be no more major changes to break things so safe to start finalizing layouts.

Thanks much for sharing your builder, has saved us much time.

**Comment by Vegetam** [comment]
Hello,

I'm working on it this weekend I may release it with more stuff as well.

I will make the card modify the color and the border and I create a section called Common Display Values based from this page 

https://getbootstrap.com/docs/4.0/utilities/display/#common-display-values

Many thanks and best regards

**Comment by oleteacher** [comment]
Thank you! Looking forward to using your new version.
