### ISSUE TITLE
element creation

### ISSUE THREAD

**Issue by kolep8** [Vegetam/BoostrapPageGenerator4#3]
When starting to drag element from sidebar, it adds horizontal scrollbar to sidebar and its scrolled right while dragging and dragged element is behind main part until mouse is released

**Comment by Vegetam** [comment]
Hi sorry for the delay.

One which browser  are you using?

Can you please make me a screenshot? Because I can't replicate this error. I'm using Chrome.

Many thanks and best regards

**Comment by oleteacher** [comment]
I think this is what @kolep8 is talking about:

https://www.useloom.com/share/f81cf5182b88454abbc9fd1ef85d71ab

Have noticed that and I too use Chrome. Hope that helps:)

**Comment by Vegetam** [comment]
Hi all , I have fixed the issue. on the index.html add style="overflow: hidden;"> at the <div class="sidebar-nav"> so should be like <div class="sidebar-nav" style="overflow: hidden;">

**Comment by Vegetam** [comment]
fixed it :) please download it or just change the div class="sidebar-nav" with the style="overflow: scroll;"> and in each so in the ul class="nav nav-list accordion-group" with the style="overflow: scroll;">
