### ISSUE TITLE
Modal Width

### ISSUE THREAD

**Issue by oleteacher** [Vegetam/BoostrapPageGenerator4#4]
Really appreciate your work on Bootstrap 4 version, very nice:)

The popup modal for the CKeditor is very narrow and cannot resize. Have tried to find CSS using dev tools so can set to a more flexible width. Would like to use something like 80% instead of px.

Where can I find the CSS controlling the modal width / height?

Thank you!

**Comment by Vegetam** [comment]
Hi,
thank you very much is to toolbox.css (.toolbox-reset .modal-content)  depends on the dimension of the screen and also inside editor.css (.toolbox-reset .modal) and unfortunately, I think you need use px.

Many thanks and best regards

**Comment by Vegetam** [comment]
Or you can do something like this.

toolbox.css
.toolbox-reset .modal-content {
    -webkit-box-shadow: 0 5px 15px rgba(0, 0, 0, 0.5);
    box-shadow: 0 5px 15px rgba(0, 0, 0, 0.5);
    width:900px;
  }
and on the editor.css
toolbox-reset .modal {
  position: fixed;
    top: 10%;
    /* left: 50%; */
    z-index: 1050;
    width: 100%;
    margin-right: 120px;
    margin-left: auto;
 }
Many thanks and best regards

**Comment by oleteacher** [comment]
Thank you @Vegetam ! I totally missed the editor.css so that was why I never got anywhere trying to modify. Got it resized but ran into this issue:

https://www.useloom.com/share/f4ab0aa8607646c0af8ced30bab4e958

When using a smaller screen and having content in rows, cannot get to editor link. Think the above video will show you better than me trying to describe:)

**Comment by Vegetam** [comment]
Hi all , I have fixed the issue. on the index.html add style="overflow: hidden;"> at the

so should be like

**Comment by oleteacher** [comment]
Thanks, but I do not see how

`so should be like "div class="sidebar-nav" style="overflow: hidden;">`

will fix the small screen issue shown in above video?

**Comment by Vegetam** [comment]
Hi practically the problem is if I use the overflow: auto; it makes this issue. I have tested it even on 22 inches of a monitor and if I add overflow: auto its make me drop and drag everywhere inside the nav the component. But Actually I noticed that I was making not possible anymore scrollable the bar. I use now the style="overflow:scroll;"> inside each nav nav-list accordion-group and sidebar-nav

**Comment by Vegetam** [comment]
Download the new code and you should not have anymore the drag and drop on the black navbar and you should scroll down for example if you are inside components and forms.

Many thanks and best regards

**Comment by oleteacher** [comment]
I think confused you sir. I am not talking about the navbar here.

The original issue here was modal width which you helped me solve. _I then tried to show you second issue (and should have opened separate issue, my bad) and you can see it in video below._

Got it resized but ran into this issue:

https://www.useloom.com/share/f4ab0aa8607646c0af8ced30bab4e958

When using a smaller screen and having content in rows, cannot get to editor link. Think the above video will show you better than me trying to describe:)

**A quick fix for issue shown in video was this mod in editor.css:**

```
.edit .demo .column .box .configuration {
  position: absolute;
  /* top: -15px; */
  top: -20px;
  /* right: 140px; */
  right: 0px;
  white-space: nowrap; }
```

**Comment by Vegetam** [comment]
Hi Sorry,

I apologize I fix this issue:

https://www.useloom.com/share/f81cf5182b88454abbc9fd1ef85d71ab

Correct your solution fix that other problem sorry for mess up -_-

Many thanks and best regards

**Comment by Vegetam** [comment]
I fixed as well the card it should fit better now on small monitor let me know it's works better and special thanks for fix the issue :)

**Comment by Vegetam** [comment]
Added you in the Readme as well :)

**Comment by oleteacher** [comment]
Glad it got fixed:) Sorry to confuse you, I should have opened separate issue for card.

Thank you again!
