### ISSUE TITLE
Docs.min.css missing

### ISSUE THREAD

**Issue by oleteacher** [Vegetam/BoostrapPageGenerator4#5]
Was just trying your latest in our classroom and noticed that docs.min is missing:

`<link href="css/docs.min.css" rel="stylesheet">`

https://github.com/Vegetam/BoostrapPageGenerator4/tree/master/4/css

See docs.min in "old folder" but not in main css folder.

Thought you may like to know:)

Great job!

**Comment by Vegetam** [comment]
Hi, Thanks a lot. 

I just added docs.min.css :) 

Many thanks and best regards

**Comment by oleteacher** [comment]
You are most welcome.

On another note: drag a 444 below the hero. They are side by side. Save the file and open. The 444 is stacked instead of side by side. Also bunch of errors in dev console. Sorry can't provide more info but must get on road for a trip.

Cheers!
